#!/bin/bash
echo "Downloading moodle"
git clone -b MOODLE_{{Version3}}_STABLE git://git.moodle.org/moodle.git  
echo "Download concluded"
echo "Copying to web folder"
sudo mv moodle /var/www/html/
sudo chown  -R root /var/www/html/moodle
sudo chmod -R 0755 /var/www/html/moodle
find /var/www/html/moodle -type f -exec chmod 0644 {}
mkdir ~/moodledata
chmod 0777 ~/moodledata

