
// Utis
const Database = require('./Database')
const Auth = require('./Auth')
const provPlatformDebug = require('debug')('provider:platform')

/**
 * @description Class representing a registered platform.
 */
class Platform {
  #platformName
  #platformUrl
  #clientId
  #authEndpoint
  #authConfig
  #ENCRYPTIONKEY
  #accesstokenEndpoint
  #kid

  /**
     * @param {string} name - Platform name.
     * @param {string} platformUrl - Platform url.
     * @param {string} clientId - Client Id generated by the platform.
     * @param {string} authenticationEndpoint - Authentication endpoint that the tool will use to authenticate within the platform.
     * @param {string} accesstokenEndpoint - Access token endpoint for the platform.
     * @param {string} kid - Key id for local keypair used to sign messages to this platform.
     * @param {string} _ENCRYPTIONKEY - Encryption key used
     * @param {Object} _authConfig - Authentication configurations for the platform.
     */
  constructor (name, platformUrl, clientId, authenticationEndpoint, accesstokenEndpoint, kid, _ENCRYPTIONKEY, _authConfig) {
    this.#authConfig = _authConfig
    this.#ENCRYPTIONKEY = _ENCRYPTIONKEY

    this.#platformName = name
    this.#platformUrl = platformUrl
    this.#clientId = clientId
    this.#authEndpoint = authenticationEndpoint
    this.#accesstokenEndpoint = accesstokenEndpoint
    this.#kid = kid
  }

  /**
     * @description Sets/Gets the platform name.
     * @param {string} [name] - Platform name.
     */
  platformName (name) {
    if (!name) return this.#platformName

    Database.Modify(false, 'platform', { platformUrl: this.#platformUrl }, { platformName: name })

    this.#platformName = name
  }

  /**
     * @description Sets/Gets the platform url.
     * @param {string} [url] - Platform url.
     */
  platformUrl (url) {
    if (!url) return this.#platformUrl

    Database.Modify(false, 'platform', { platformUrl: this.#platformUrl }, { platformUrl: url })

    this.#platformUrl = url
  }

  /**
     * @description Sets/Gets the platform client id.
     * @param {string} [clientId] - Platform client id.
     */
  platformClientId (clientId) {
    if (!clientId) return this.#clientId

    Database.Modify(false, 'platform', { platformUrl: this.#platformUrl }, { clientId: clientId })

    this.#clientId = clientId
  }

  /**
     * @description Gets the platform key_id.
     */
  platformKid () {
    return this.#kid
  }

  /**
     * @description Gets the RSA public key assigned to the platform.
     *
     */
  async platformPublicKey () {
    let key = await Database.Get(this.#ENCRYPTIONKEY, 'publickey', { kid: this.#kid })
    return key[0].key
  }

  /**
     * @description Gets the RSA private key assigned to the platform.
     *
     */
  async platformPrivateKey () {
    let key = await Database.Get(this.#ENCRYPTIONKEY, 'privatekey', { kid: this.#kid })
    return key[0].key
  }

  /**
     * @description Sets/Gets the platform authorization configurations used to validate it's messages.
     * @param {string} method - Method of authorization "RSA_KEY" or "JWK_KEY" or "JWK_SET".
     * @param {string} key - Either the RSA public key provided by the platform, or the JWK key, or the JWK keyset address.
     */
  platformAuthConfig (method, key) {
    if (!method && !key) return this.#authConfig

    if (method !== 'RSA_KEY' && method !== 'JWK_KEY' && method !== 'JWK_SET') throw new Error('Invalid message validation method. Valid methods are "RSA_KEY", "JWK_KEY", "JWK_SET"')

    if (!key) throw new Error('Missing secong argument key or keyset_url.')

    this.#authConfig = {
      method: method,
      key: key
    }

    Database.Modify(false, 'platform', { platformUrl: this.#platformUrl }, { authConfig: this.#authConfig })
  }

  /**
     * @description Sets/Gets the platform authorization endpoint used to perform the OIDC login.
     * @param {string} [authEndpoint] - Platform authorization endpoint.
     */
  platformAuthEndpoint (authEndpoint) {
    if (!authEndpoint) return this.#authEndpoint

    Database.Modify(false, 'platform', { platformUrl: this.#platformUrl }, { authEndpoint: authEndpoint })

    this.#authEndpoint = authEndpoint
  }

  /**
     * @description Sets/Gets the platform access token endpoint used to authenticate messages to the platform.
     * @param {string} [accesstokenEndpoint] - Platform access token endpoint.
     */
  platformAccessTokenEndpoint (accesstokenEndpoint) {
    if (!accesstokenEndpoint) return this.#accesstokenEndpoint

    Database.Modify(false, 'platform', { platformUrl: this.#platformUrl }, { accesstokenEndpoint: accesstokenEndpoint })

    this.#accesstokenEndpoint = accesstokenEndpoint
  }

  /**
     * @description Returns a promise that resolves into the platform's access token or generates a new one.
     */
  async platformAccessToken () {
    let token = await Database.Get(this.#ENCRYPTIONKEY, 'accesstoken', { platformUrl: this.#platformUrl })

    if (!token) {
      provPlatformDebug('Access_token for ' + this.#platformUrl + ' not found')
      provPlatformDebug('Attempting to generate new access_token for ' + this.#platformUrl)
      let res = await Auth.getAccessToken(this, this.#ENCRYPTIONKEY)
      return res
    } else {
      provPlatformDebug('Access_token found')
      if ((Date.now() - token[0].createdAt) / 1000 > token[0].expires_in) {
        provPlatformDebug('Token expired')
        provPlatformDebug('Access_token for ' + this.#platformUrl + ' not found')
        provPlatformDebug('Attempting to generate new access_token for ' + this.#platformUrl)
        let res = await Auth.getAccessToken(this, this.#ENCRYPTIONKEY)
        return res
      }
      return token[0].token
    }
  }

  /**
   * @description Deletes a registered platform.
   */
  async remove () {
    return Promise.all([Database.Delete('platform', { platformUrl: this.#platformUrl }), Database.Delete('publickey', { kid: this.#kid }), Database.Delete('privatekey', { kid: this.#kid })])
  }
}

module.exports = Platform
